# Gems host
source 'http://rubygems.org'

## Ruby Framework and Builder
################################################################################
gem 'rails', '>=3.1.0.rc4'       # At least 3.1.0.rc
gem 'rake', '>=0.9.2'            # Rake 0.9 is incompatible with Rails 3.0.9
# gem 'rails', :git => 'git://github.com/rails/rails.git' # Edge Rails
# ------------------------------------------------------------------------------


## Database Drivers
################################################################################
gem 'mongo_ext', '~> 0.19.3'    # MongoDB - Document Oriented Database engine
gem 'bson_ext', '~> 1.3.1'      # MongoDB BSON serialization
gem 'sqlite3', '~> 1.3.3'       # SQL-Lite flat Database engine
gem 'mysql2', '~> 0.3.6'        # MySQL Database engine
# ------------------------------------------------------------------------------


## ActiveRecord Extensions and Object Mapper
################################################################################
gem 'mongo_mapper', '~> 0.9.1'  # MongoDB - Object Mapper
#gem 'friendly_id'              # Human readable URLs
#gem 'validates_existence'      # Validation of model associations
# ------------------------------------------------------------------------------


## Enhanced Debugging
################################################################################
# gem 'ruby-debug19', :require => 'ruby-debug'
gem 'hirb'                      # Better console formatting. Needs .hirbrc
# ------------------------------------------------------------------------------


## Server & Deployment
################################################################################
gem 'capistrano'                # Deployment manager
gem 'unicorn'                   # Use unicorn as the web server


## Asset template engines
################################################################################
gem 'sass-rails', '~> 3.1.0.rc' # Sass (css replacement)
gem 'haml'                      # Haml (html/erb replacement)
gem 'haml-rails'                # Haml generators for Rails 3
gem 'coffee-script'             # coffee-script (javascript replacement)
gem 'jquery-rails'              # jQuery support for Rails
gem 'uglifier'                  # UglifyJS JavaScript compressor
# ------------------------------------------------------------------------------

## HTML/CSS framework and boilerplate
################################################################################
gem 'compass'                   # Compass (Sass watcher)
gem 'html5-boilerplate'         # HTML5 Boilerplate builder
gem 'compass-960-plugin'        # 960.gs Grid plugin for Compass
# ------------------------------------------------------------------------------


## Authentification and Role Based Access Control Lists
################################################################################
gem 'devise', '~> 1.4.2'        # User authentication (accounts)
gem 'hpricot', '~> 0.8.4'       # For Devise view generation (HTML parser)
gem 'ruby_parser', '~> 2.0.6'   # For Devise view generation (Ruby parser)
gem 'cancan', '~> 1.6.5'        # User authorization (permissions)
# ------------------------------------------------------------------------------


## Outsourced Business Logic
################################################################################
gem 'acts_as_mongo_rateable', '~> 0.2.1' # Balanced-, Bayesian weighting system 
# ------------------------------------------------------------------------------


## Optional gems below
################################################################################
# gem 'will_paginate', '~> 2.3.15'    # Pagination of long lists
# gem 'paperclip', '~> 2.3.15'        # File upload management
# gem 'mongoid-paperclip', '~> 0.0.5' # File upload management for MongoDB
# gem 'vestal_versions', '~> 1.0.2'   # To track changes to pages and other objects
# gem 'paper_trail', '~> 2.2.8'       # To track changes to pages and other objects


group :development, :test do
  gem 'factory_girl_rails'
  gem 'factory_girl_generator'
  gem 'rspec-rails'
  gem 'rcov'
  gem 'forgery'                     # Easy generation of fake data
  gem 'turn', :require => false
end
